{% set name = "bdw-gc" %}
{% set version = "7.6.4" %}
{% set sha256 = "b9f30bd5759e4282fdb161414a1b23845c63b725e8ed40fc110d0859a4396b81"%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: gc-{{ version }}.tar.gz
  url: https://github.com/ivmai/bdwgc/releases/download/v{{ version }}/gc-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - autoconf
    - automake
    - libtool
    - pkg-config
    - libatomic_ops

test:
  commands:
    - test -e $PREFIX/include/gc.h
    - test -e $PREFIX/lib/libgc.a
    - test -e $PREFIX/lib/libgc.dylib  # [osx]

about:
  home: http://www.hboehm.info/gc/
  license: Custom
  summary: Garbage collector for C and C++.

extra:
  recipe-maintainers:
    - stefan-balke
