{% set version = "8.2.8" %}

package:
  name: bdw-gc
  version: {{ version }}

source:
  url: https://github.com/ivmai/bdwgc/archive/v{{ version }}.tar.gz
  sha256: 3de0e3d456103a8409927ac16aa45d7b7647dd613e1f212019deab27713445cb

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('bdw-gc') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
    - make
  host:
    # Uses the static library
    - libatomic_ops

test:
  commands:
    - test -e $PREFIX/include/gc.h
    - test -e $PREFIX/lib/libgc.so     # [linux]
    - test -e $PREFIX/lib/libgc.dylib  # [osx]

about:
  home: http://www.hboehm.info/gc/
  license: Custom
  summary: Garbage collector for C and C++.

extra:
  recipe-maintainers:
    - danielnachun
    - isuruf
    - stefan-balke
