{% set name = "bdw-gc" %}
{% set version = "7.6.4" %}
{% set sha256 = "1f85bf6d4aaa3fb12fe0178b13d9685e2d0c3a4d115dea5f831c54deafa3f6db"%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: gc-{{ version }}.tar.gz
  url: https://github.com/ivmai/bdwgc/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - autoconf
    - automake
    - libtool
    - pkg-config
    - libatomic_ops

test:
  commands:
    - test -e $PREFIX/include/gc.h
    - test -e $PREFIX/lib/libgc.a
    - test -e $PREFIX/lib/libgc.dylib  # [osx]

about:
  home: http://www.hboehm.info/gc/
  license: Custom
  summary: Garbage collector for C and C++.

extra:
  recipe-maintainers:
    - stefan-balke
