{% set name = "bdw-gc" %}
{% set version = "8.0.2" %}
{% set sha256 = "711ef890f7bc473c0b043c6372c09b8b747ac5141c01a32182ccc393f3b272b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: gc-{{ version }}.tar.gz
  url: https://github.com/ivmai/bdwgc/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage('bdw-gc') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
  host:
    # Uses the static library
    - libatomic_ops

test:
  commands:
    - test -e $PREFIX/include/gc.h
    - test -e $PREFIX/lib/libgc.a
    - test -e $PREFIX/lib/libgc.dylib  # [osx]

about:
  home: http://www.hboehm.info/gc/
  license: Custom
  summary: Garbage collector for C and C++.

extra:
  recipe-maintainers:
    - isuruf
    - stefan-balke
