{% set version = "8.2.10" %}

package:
  name: bdw-gc
  version: {{ version }}

source:
  url: https://github.com/ivmai/bdwgc/archive/v{{ version }}.tar.gz
  sha256: 5858a417ab3eaac2add0daf79cd29ddf248c9f648e6c08092b775dcbfcbe1edb

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('bdw-gc') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - autoconf            # [unix]
    - automake            # [unix]
    - libtool             # [unix]
    - pkg-config          # [unix]
    - make                # [unix]
    - cmake               # [win]
    - ninja               # [win]
  host:
    - libatomic_ops       # [win]

test:
  commands:
    - test -e $PREFIX/include/gc.h              # [unix]
    - test -e $PREFIX/lib/libgc${SHLIB_EXT}     # [unix]
    - if not exist %LIBRARY_INC%\gc.h exit 1    # [win]
    - if not exist %LIBRARY_BIN%\gc.dll exit 1  # [win]

about:
  home: http://www.hboehm.info/gc/
  license: LicenseRef-Bdwgc-Mit-Like
  license_file: LICENSE
  summary: Garbage collector for C and C++.

extra:
  recipe-maintainers:
    - danielnachun
    - isuruf
    - stefan-balke
