{% set name = "bdw-gc" %}
{% set version = "8.2.0" %}
{% set sha256 = "c7f03093f72190cf5ed427886006b72ab8ca1f45b509c0cb9c8f97cee497d7d3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: gc-{{ version }}.tar.gz
  url: https://github.com/ivmai/bdwgc/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('bdw-gc') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
    - make
  host:
    # Uses the static library
    - libatomic_ops

test:
  commands:
    - test -e $PREFIX/include/gc.h
    - test -e $PREFIX/lib/libgc.so     # [linux]
    - test -e $PREFIX/lib/libgc.dylib  # [osx]

about:
  home: http://www.hboehm.info/gc/
  license: LicenseRef-MIT-like
  license_file: LICENSE
  summary: Garbage collector for C and C++.

extra:
  recipe-maintainers:
    - isuruf
    - stefan-balke
