schema_version: 1

context:
  version: "8.2.12"

package:
  name: bdw-gc
  version: ${{ version }}

source:
  url: https://github.com/ivmai/bdwgc/archive/v${{ version }}.tar.gz
  sha256: d09001f45dabf1c29a5df3e63020a4bab5ad4aad69137bb07100c717e2ecba0b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: unix
      then:
        - autoconf
        - automake
        - libtool
        - pkg-config
        - make
        - cmake
        - ninja
  host:
    - if: win
      then: libatomic_ops
  run_exports:
    - ${{ pin_subpackage('bdw-gc') }}

tests:
  - script:
      - if: unix
        then:
          - test -e $PREFIX/include/gc.h
          - test -e $PREFIX/lib/libgc${SHLIB_EXT}
      - if: win
        then:
          - if not exist %LIBRARY_INC%\gc.h exit 1
          - if not exist %LIBRARY_BIN%\gc.dll exit 1

about:
  license: LicenseRef-Bdwgc-Mit-Like
  license_file: LICENSE
  summary: Garbage collector for C and C++.
  homepage: http://www.hboehm.info/gc/

extra:
  recipe-maintainers:
    - danielnachun
    - isuruf
    - stefan-balke
