travis:
  secure:
    BINSTAR_TOKEN: lLaf0kIZKb8q/8I3eW8SxkYSb5H8WrZiN7ArWqmC+hNATGJ/kFQEgdfzjcsnTug+ZCD25G/06A8XQILeTCnTGT0cVgI846wE7QnoZercWq7rSnufxfsVseao78bqPKGoXwpL+DNrnPxS6qYFVeBS4PEmsCDi1PpF2MuNT7kM1XlbNYa4xOCtfIrIkoS8D4qSgt0sRP50Yn+aY/jSnrOxGhh9KFHm8//7h9L7xaxDrtof4bPljgezauwc108KXOYJb2rQGmXtv+JpAnZBOf2+9IZbVAbQhQ4lwTBS4PFrWTJgeQxFp5LQ4+wK2csfb1IZ+BR6zjF0jTvx94VtrfKCYYXsPjRG2xdrcf1gFHpYic6xa6TPanVKQmwzHZzEQh98xrjt6Dqcn0vU+iCxxVjjZEXCTyCJnzihKJ1eP3JBaN+QI2pf0tQEe7Z7dOTDJC/f1QtViw8qWFPN1ezw7TDRWUPKyYWxj3D/BwkfFruK0/aP374gKLaA/WNs1V6YZEQZmz0vf90yK4GjIQI36x1VApuuczg5y8glIB7TwIcp1vxVCelky7GfTUZjEgPxczREtRn2MSoHzr2XeC8k1T0mQW859wI4+xqatYNeW6e5BnQoAAP+tsFzCNsnZtOan5ItLCwtQOtzolNyEFtF7QulQiK1pqRfaLtFQL48ywwtrWQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
